/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  karmapay: [
    {
      type: 'category',
      label: 'Introduction to Karmapay',
      items: ['karmapay/karmapay'],
    },
    {
      type: 'category',
      label: 'How KarmaPay Works?',
      items: ['karmapay/working/workflow'],
    },
    {
      type: 'category',
      label: 'Getting started with Karmapay',
      items: ['karmapay/getting-started/account-setup', 'karmapay/getting-started/razorpay', 'karmapay/getting-started/phonepe', 'karmapay/getting-started/stripe'],
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: ['karmapay/api-documentation/create-order'],
    },
  ],

  healthKareAI: [
    {
      type: 'category',
      label: 'HealthKareAI AUTH APIs',
      items: ['HealthKareAI/login', 'HealthKareAI/register', 'HealthKareAI/verifyOTP'],
    },
    {
      type: 'category',
      label: 'HealthKareAI User APIs',
      items: ['HealthKareAI/update_phone', 'HealthKareAI/update_email', 'HealthKareAI/update_password', 'HealthKareAI/update_city', 'HealthKareAI/update_role', 'HealthKareAI/get_user'],
    },
    {
      type: 'category',
      label: 'Doctor APIs',
      items: ['HealthKareAI/doctor/login', 'HealthKareAI/doctor/register', 'HealthKareAI/doctor/verifyOTP']
    },
    {
      type: 'category',
      label: 'Hospital APIs',
      items: ['HealthKareAI/hospital/login', 'HealthKareAI/hospital/register', 'HealthKareAI/hospital/verifyOTP', 'HealthKareAI/hospital/getDetails']
    },
    {
      type: 'category',
      label: 'Error Codes',
      items: ['HealthKareAI/error_codes'],
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
